Repository lakesoul-io/LakeSoul, pull requests merged in 2023-07, with the labels that each got.

#263 Modify mysqlcdc sort key generation way
  lakesoul-flink/src/main/java/org/apache/flink/lakesoul/entry/MysqlCdc.java
  lakesoul-flink/src/main/java/org/apache/flink/lakesoul/types/BinarySourceRecord.java
Labels: flink

#265 [Flink] Fix flink reader npe
  .github/workflows/maven-test.yml
  docker/lakesoul-docker-compose-env/docker-compose.yml
  lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/dao/DataCommitInfoDao.java
  lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/dao/NamespaceDao.java
  lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/dao/PartitionInfoDao.java
  lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/dao/TableInfoDao.java
  lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/dao/TableNameIdDao.java
  lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/dao/TablePathIdDao.java
  lakesoul-flink/src/main/java/org/apache/flink/lakesoul/sink/committer/LakeSoulSinkCommitter.java
  lakesoul-flink/src/main/java/org/apache/flink/lakesoul/sink/committer/LakeSoulSinkGlobalCommitter.java
  lakesoul-flink/src/main/java/org/apache/flink/lakesoul/sink/state/LakeSoulMultiTableSinkCommittable.java
  lakesoul-flink/src/main/java/org/apache/flink/lakesoul/sink/state/LakeSoulMultiTableSinkGlobalCommittable.java
  lakesoul-flink/src/main/java/org/apache/flink/lakesoul/sink/writer/NativeParquetWriter.java
  lakesoul-flink/src/main/java/org/apache/flink/lakesoul/source/LakeSoulDynamicSplitEnumerator.java
  lakesoul-flink/src/main/java/org/apache/flink/lakesoul/source/LakeSoulOneSplitRecordsReader.java
  lakesoul-flink/src/main/java/org/apache/flink/lakesoul/source/LakeSoulSource.java
  lakesoul-flink/src/main/java/org/apache/flink/lakesoul/source/LakeSoulSplit.java
  lakesoul-flink/src/main/java/org/apache/flink/lakesoul/source/LakeSoulSplitReader.java
  lakesoul-flink/src/main/scala/com/dmetasoul/lakesoul/meta/DataOperation.scala
  lakesoul-flink/src/test/java/org/apache/flink/lakesoul/test/PostgresContainerHelper.java
  lakesoul-flink/src/test/java/org/apache/flink/lakesoul/test/fail/LakeSoulSinkFailTest.java
  lakesoul-flink/src/test/java/org/apache/flink/lakesoul/test/fail/LakeSoulSourceFailTest.java
Labels: bug, flink

#267 Refine meta partition values
  lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/DBConfig.java
  lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/DBManager.java
  lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/DBUtil.java
  lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/dao/PartitionInfoDao.java
  lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/entity/DataCommitInfo.java
  lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/entity/PartitionInfo.java
  lakesoul-flink/src/main/java/com/dmetasoul/lakesoul/meta/external/mysql/MysqlDBManager.java
  lakesoul-flink/src/main/java/org/apache/flink/lakesoul/connector/LakeSoulPartition.java
  lakesoul-flink/src/main/java/org/apache/flink/lakesoul/connector/LakeSoulPartitionFetcherContextBase.java
  lakesoul-flink/src/main/java/org/apache/flink/lakesoul/metadata/LakeSoulCatalog.java
  lakesoul-flink/src/main/java/org/apache/flink/lakesoul/sink/committer/LakeSoulSinkCommitter.java
  lakesoul-flink/src/main/java/org/apache/flink/lakesoul/sink/committer/LakeSoulSinkGlobalCommitter.java
  lakesoul-flink/src/main/java/org/apache/flink/lakesoul/source/LakeSoulLookupTableSource.java
  lakesoul-flink/src/main/java/org/apache/flink/lakesoul/tool/FlinkUtil.java
  lakesoul-flink/src/main/java/org/apache/flink/lakesoul/tool/LakeSoulSinkOptions.java
  lakesoul-flink/src/main/scala/com/dmetasoul/lakesoul/meta/DataOperation.scala
  lakesoul-flink/src/main/scala/com/dmetasoul/lakesoul/meta/MetaVersion.scala
  lakesoul-flink/src/test/java/org/apache/flink/lakesoul/test/fail/LakeSoulSinkFailTest.java
  lakesoul-spark/src/main/scala/com/dmetasoul/lakesoul/meta/MetaCommit.scala
  lakesoul-spark/src/main/scala/com/dmetasoul/lakesoul/meta/MetaUtils.scala
  lakesoul-spark/src/main/scala/com/dmetasoul/lakesoul/meta/MetaVersion.scala
  lakesoul-spark/src/main/scala/com/dmetasoul/lakesoul/spark/compaction/CompactionTask.scala
  lakesoul-spark/src/main/scala/org/apache/spark/sql/execution/datasources/v2/merge/parquet/batch/merge_operator/MergeMultiFileWithOperator.scala
  lakesoul-spark/src/main/scala/org/apache/spark/sql/lakesoul/kafka/KafkaStream.scala
Labels: enhancement

#269 [Flink]Check schema migration at GlobalCommitter
  lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/DBConfig.java
  lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/DBManager.java
  lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/dao/PartitionInfoDao.java
  lakesoul-flink/src/main/java/org/apache/flink/lakesoul/sink/committer/LakeSoulSinkGlobalCommitter.java
  lakesoul-flink/src/main/java/org/apache/flink/lakesoul/tool/LakeSoulSinkOptions.java
  lakesoul-flink/src/test/java/org/apache/flink/lakesoul/test/MockLakeSoulCatalog.java
  lakesoul-flink/src/test/java/org/apache/flink/lakesoul/test/MockTableSource.java
  lakesoul-flink/src/test/java/org/apache/flink/lakesoul/test/fail/LakeSoulSinkFailTest.java
  lakesoul-flink/src/test/java/org/apache/flink/lakesoul/test/fail/LakeSoulSourceFailTest.java
  lakesoul-flink/src/test/java/org/apache/flink/lakesoul/test/schema/SchemaMigrationTest.java
  lakesoul-spark/src/test/scala/org/apache/spark/sql/lakesoul/DDLSuite.scala
  native-io/.gitignore
  native-io/Cargo.lock
  native-io/lakesoul-io-java/src/main/scala/org/apache/spark/sql/arrow/DataTypeCastUtils.scala
  native-io/lakesoul-io/src/constant.rs
  native-io/lakesoul-io/src/lakesoul_writer.rs
  native-io/lakesoul-io/src/transform.rs
Labels: flink, native-io

#274 [RBAC] PG workspace implementation
  lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/DBConnector.java
  lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/DBManager.java
  lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/DBUtil.java
  lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/GlobalConfig.java
  lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/dao/DataCommitInfoDao.java
  lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/dao/NamespaceDao.java
  lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/dao/PartitionInfoDao.java
  lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/dao/TableInfoDao.java
  lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/dao/TableNameIdDao.java
  lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/dao/TablePathIdDao.java
  lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/entity/DataCommitInfo.java
  lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/entity/Namespace.java
  lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/entity/PartitionInfo.java
  lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/entity/TableInfo.java
  lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/entity/TableNameId.java
  lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/entity/TablePathId.java
  lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/rbac/AuthZEnforcer.java
  lakesoul-spark/src/test/scala/org/apache/spark/sql/lakesoul/DataFrameWriterV2Suite.scala
  script/meta_init.sql
  script/meta_rbac_add_domain.sql
  script/meta_rbac_add_user.sql
  script/meta_rbac_init.sql
Labels: enhancement

#276 [Metadata] refractor metadata entity with protobuf code-gen
  .github/workflows/flink-cdc-test.yml
  .github/workflows/maven-test.yml
  .github/workflows/native-build.yml
  .gitignore
  lakesoul-common/pom.xml
  lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/DBConfig.java
  lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/DBManager.java
  lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/DBUtil.java
  lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/dao/DataCommitInfoDao.java
  lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/dao/NamespaceDao.java
  lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/dao/PartitionInfoDao.java
  lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/dao/TableInfoDao.java
  lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/dao/TableNameIdDao.java
  lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/dao/TablePathIdDao.java
  lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/entity/DataCommitInfo.java
  lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/entity/DataFileOp.java
  lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/entity/MetaInfo.java
  lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/entity/Namespace.java
  lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/entity/PartitionInfo.java
  lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/entity/TableInfo.java
  lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/entity/TableNameId.java
  lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/entity/TablePathId.java
  lakesoul-flink/pom.xml
  lakesoul-flink/src/main/java/com/dmetasoul/lakesoul/meta/external/ExternalDBManager.java
  lakesoul-flink/src/main/java/com/dmetasoul/lakesoul/meta/external/mysql/MysqlDBManager.java
  lakesoul-flink/src/main/java/org/apache/flink/lakesoul/metadata/LakeSoulCatalog.java
  lakesoul-flink/src/main/java/org/apache/flink/lakesoul/sink/committer/LakeSoulSinkCommitter.java
  lakesoul-flink/src/main/java/org/apache/flink/lakesoul/tool/FlinkUtil.java
  lakesoul-flink/src/main/scala/com/dmetasoul/lakesoul/meta/DataOperation.scala
  lakesoul-flink/src/main/scala/com/dmetasoul/lakesoul/meta/MetaVersion.scala
  lakesoul-flink/src/test/java/org/apache/flink/lakesoul/test/LakeSoulCatalogTest.java
  lakesoul-flink/src/test/java/org/apache/flink/lakesoul/test/LakeSoulCatalogTestBase.java
  lakesoul-flink/src/test/java/org/apache/flink/lakesoul/test/schema/SchemaMigrationTest.java
  lakesoul-spark/pom.xml
  lakesoul-spark/src/main/scala/com/dmetasoul/lakesoul/meta/DataOperation.scala
  lakesoul-spark/src/main/scala/com/dmetasoul/lakesoul/meta/MetaCommit.scala
  lakesoul-spark/src/main/scala/com/dmetasoul/lakesoul/meta/MetaVersion.scala
  lakesoul-spark/src/main/scala/com/dmetasoul/lakesoul/meta/StreamingRecord.scala
  lakesoul-spark/src/main/scala/org/apache/spark/sql/lakesoul/TransactionCommit.scala
  lakesoul-spark/src/main/scala/org/apache/spark/sql/lakesoul/kafka/KafkaStream.scala
  native-io/Cargo.lock
  native-io/lakesoul-io-java/pom.xml
  native-metadata/.gitignore
  native-metadata/Cargo.toml
  native-metadata/lakesoul-metadata-c/Cargo.toml
  native-metadata/lakesoul-metadata-c/src/lib.rs
  native-metadata/lakesoul-metadata/Cargo.toml
  native-metadata/lakesoul-metadata/build.rs
  native-metadata/lakesoul-metadata/src/main.rs
  native-metadata/proto/Cargo.toml
  native-metadata/proto/build.rs
  native-metadata/proto/src/entity.proto
  native-metadata/proto/src/lib.rs
  script/meta_cleanup.sql
  script/meta_init.sql
Labels: native-io, python

#277 format table path with hdfs configuration
  lakesoul-flink/src/main/java/org/apache/flink/lakesoul/types/BinarySourceRecord.java
Labels: flink

#279 [Doc] Add Spark session catalog doc
  javadoc/README.md
  website/blog/2023-04-21-lakesoul-2.2.0-release/index.md
  website/docs/00-intro.md
  website/docs/01-Getting Started/01-setup-local-env.md
  website/docs/01-Getting Started/02-docker-compose.mdx
  website/docs/02-Tutorials/01-consume-cdc-via-spark-streaming.md
  website/docs/02-Tutorials/02-flink-cdc-sink/index.md
  website/docs/02-Tutorials/03-snapshot-manage.md
  website/docs/02-Tutorials/04-data-mount-to-hive.md
  website/docs/02-Tutorials/05-upsert-and-merge-udf.md
  website/docs/02-Tutorials/06-mutil-stream-merge.md
  website/docs/02-Tutorials/07-kafka-topics-data-to-lakesoul.md
  website/docs/02-Tutorials/08-incremental-query.md
  website/docs/03-Usage Docs/01-setup-meta-env.md
  website/docs/03-Usage Docs/02-setup-spark.md
  website/docs/03-Usage Docs/03-api-docs.md
  website/docs/03-Usage Docs/04-cdc-ingestion-table.mdx
  website/docs/03-Usage Docs/05-flink-cdc-sync.md
  website/docs/03-Usage Docs/06-flink-lakesoul-connector.md
  website/docs/03-Usage Docs/08-auto-compaction-task.md
  website/i18n/zh-Hans/docusaurus-plugin-content-blog/2023-04-21-lakesoul-2.2.0-release/index.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/00-intro.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/01-Getting Started/01-setup-local-env.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/01-Getting Started/02-docker-compose.mdx
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/02-Tutorials/01-consume-cdc-via-spark-streaming.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/02-Tutorials/02-flink-cdc-sink/index.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/02-Tutorials/03-snapshot-manage.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/02-Tutorials/04-data-mount-to-hive.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/02-Tutorials/05-upsert-and-merge-udf.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/02-Tutorials/06-mutil-stream-merge.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/02-Tutorials/07-kafka-topics-data-to-lakesoul.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/02-Tutorials/08-incremental-query.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/02-Tutorials/09-flink-sql-tutorial.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/03-Usage Docs/01-setup-meta-env.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/03-Usage Docs/02-setup-spark.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/03-Usage Docs/03-api-docs.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/03-Usage Docs/04-cdc-ingestion-table.mdx
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/03-Usage Docs/05-flink-cdc-sync.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/03-Usage Docs/06-flink-lakesoul-connector.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/03-Usage Docs/08-auto-compaction-task.md
Labels: documentation

#281 [Release] Add 2.3.0 release blog
  website/blog/2023-07-17-lakesoul-2.3.0-release/index.md
  website/i18n/zh-Hans/docusaurus-plugin-content-blog/2023-07-17-lakesoul-2.3.0-release/index.md
Labels: documentation, release

#282 [NativeIO] Upgrade datafusion to 27
  .github/workflows/website-build.yml
  .github/workflows/website-publish.yml
  lakesoul-spark/src/test/scala/org/apache/spark/sql/lakesoul/commands/UpdateSuiteBase.scala
  native-io/Cargo.lock
  native-io/lakesoul-io-c/Cargo.toml
  native-io/lakesoul-io-c/src/lib.rs
  native-io/lakesoul-io-java/src/main/java/com/dmetasoul/lakesoul/lakesoul/io/NativeIOBase.java
  native-io/lakesoul-io-java/src/main/java/com/dmetasoul/lakesoul/lakesoul/io/NativeIOReader.java
  native-io/lakesoul-io/Cargo.toml
  native-io/lakesoul-io/src/constant.rs
  native-io/lakesoul-io/src/default_column_stream/empty_schema_stream.rs
  native-io/lakesoul-io/src/default_column_stream/mod.rs
  native-io/lakesoul-io/src/filter/parser.rs
  native-io/lakesoul-io/src/hdfs/mod.rs
  native-io/lakesoul-io/src/lakesoul_io_config.rs
  native-io/lakesoul-io/src/lakesoul_reader.rs
  native-io/lakesoul-io/src/lakesoul_writer.rs
  native-io/lakesoul-io/src/sorted_merge/merge_operator.rs
  native-io/lakesoul-io/src/sorted_merge/sorted_stream_merger.rs
  native-io/lakesoul-io/src/transform.rs
Labels: enhancement

#287 [Flink] implement filter pushdown and fix partition pushdown in flink
  README.md
  lakesoul-flink/pom.xml
  lakesoul-flink/src/main/java/org/apache/flink/lakesoul/metadata/LakeSoulCatalog.java
  lakesoul-flink/src/main/java/org/apache/flink/lakesoul/sink/bucket/CdcPartitionComputer.java
  lakesoul-flink/src/main/java/org/apache/flink/lakesoul/sink/state/LakeSoulSinkGlobalCommittableSerializer.java
  lakesoul-flink/src/main/java/org/apache/flink/lakesoul/source/LakeSoulDynamicSplitEnumerator.java
  lakesoul-flink/src/main/java/org/apache/flink/lakesoul/source/LakeSoulLookupTableSource.java
  lakesoul-flink/src/main/java/org/apache/flink/lakesoul/source/LakeSoulOneSplitRecordsReader.java
  lakesoul-flink/src/main/java/org/apache/flink/lakesoul/source/LakeSoulSource.java
  lakesoul-flink/src/main/java/org/apache/flink/lakesoul/source/LakeSoulSplitReader.java
  lakesoul-flink/src/main/java/org/apache/flink/lakesoul/source/ParquetFilters.java
  lakesoul-flink/src/main/java/org/apache/flink/lakesoul/table/LakeSoulTableSource.java
  lakesoul-flink/src/main/java/org/apache/flink/lakesoul/types/BinarySourceRecord.java
  lakesoul-flink/src/test/java/org/apache/flink/lakesoul/test/flinkSource/BatchReadSuite.java
  lakesoul-flink/src/test/java/org/apache/flink/lakesoul/test/flinkSource/TestUtils.java
  lakesoul-spark/src/test/scala/org/apache/spark/sql/lakesoul/TableCreationTests.scala
  native-io/Cargo.lock
  native-io/lakesoul-io/Cargo.toml
  native-io/lakesoul-io/src/default_column_stream/mod.rs
  native-io/lakesoul-io/src/lakesoul_io_config.rs
  native-io/lakesoul-io/src/lakesoul_reader.rs
  native-io/lakesoul-io/src/lakesoul_writer.rs
  native-io/lakesoul-io/src/transform.rs
Labels: bug, enhancement

#291 [Python][NativeIO] Add C interface definition
  .github/workflows/flink-cdc-test.yml
  .gitignore
  lakesoul-flink/src/test/java/org/apache/flink/lakesoul/test/fail/LakeSoulSinkFailTest.java
  native-io/Cargo.lock
  native-io/lakesoul-io-c/Cargo.toml
  native-io/lakesoul-io-c/build.rs
Labels: enhancement, python

#290 [NativeIO] update arrow version
  lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/DBConnector.java
  lakesoul-spark/src/test/scala/org/apache/spark/sql/lakesoul/commands/UpdateSuiteBase.scala
  native-io/lakesoul-io/src/lakesoul_io_config.rs
  website/docs/03-Usage Docs/01-setup-meta-env.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/03-Usage Docs/01-setup-meta-env.md
Labels: documentation, enhancement
