Repository lakesoul-io/LakeSoul, pull requests merged in 2023-09, with the labels that each got.

#321 [RBAC] Set hdfs dir owner
  .github/workflows/flink-cdc-hdfs-test.yml
  .github/workflows/flink-cdc-test.yml
  .github/workflows/maven-test.yml
  .github/workflows/presto-cdc-test.yml
  docker/lakesoul-docker-compose-env/docker-compose.yml
  lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/DBUtil.java
  lakesoul-flink/pom.xml
  lakesoul-flink/src/main/java/org/apache/flink/lakesoul/metadata/LakeSoulCatalog.java
  lakesoul-flink/src/main/java/org/apache/flink/lakesoul/tool/FlinkUtil.java
  lakesoul-flink/src/test/java/com/dmetasoul/lakesoul/meta/LakeSoulRBACTest.java
  lakesoul-flink/src/test/java/org/apache/flink/lakesoul/test/LakeSoulCatalogDatabaseTest.java
  lakesoul-flink/src/test/java/org/apache/flink/lakesoul/test/LakeSoulFlinkTestBase.java
  lakesoul-flink/src/test/java/org/apache/flink/lakesoul/test/LakeSoulPrestoTest.java
  lakesoul-flink/src/test/java/org/apache/flink/lakesoul/test/benchmark/LakeSoulDataGenSourceTable.java
  lakesoul-spark/pom.xml
  lakesoul-spark/src/main/java/org/apache/spark/sql/execution/datasources/parquet/NativeVectorizedReader.java
  lakesoul-spark/src/main/scala/org/apache/spark/sql/lakesoul/commands/CreateTableCommand.scala
  lakesoul-spark/src/main/scala/org/apache/spark/sql/vectorized/NativeIOUtils.scala
  lakesoul-spark/src/test/scala/com/dmetasoul/lakesoul/meta/RBACOperationSuite.scala
  script/meta_rbac_init_domains_for_test.sql
  script/meta_rbac_init_for_local_test.sh
  script/meta_rbac_init_users_for_test.sql
Labels: enhancement

#327 [Python] Examples using Python API for AI model training
  python/examples/README.md
  python/examples/food101/README.md
  python/examples/food101/embedding.py
  python/examples/food101/import_data.py
  python/examples/food101/search.py
  python/examples/imdb/README.md
  python/examples/imdb/accuracy/accuracy.py
  python/examples/imdb/import_data.py
  python/examples/imdb/inference.py
  python/examples/imdb/train.py
  python/examples/import_titanic.py
  python/examples/lakesoul-docker-compose-env/docker-compose.yml
  python/examples/lakesoul-docker-compose-env/meta_cleanup.sql
  python/examples/lakesoul-docker-compose-env/meta_init.sql
  python/examples/lakesoul-docker-compose-env/mysql_init.sql
  python/examples/lakesoul.properties
  python/examples/lakesoul_env.sh
  python/examples/requirements.txt
  python/examples/titanic/README.md
  python/examples/titanic/feature_transform.py
  python/examples/titanic/import_data.py
  python/examples/titanic/train.py
Labels: documentation, python

#328 update docs and readme for release 2.4
  README-CN.md
  README.md
  website/docs/01-Getting Started/01-setup-local-env.md
  website/docs/01-Getting Started/02-docker-compose.mdx
  website/docs/02-Tutorials/02-flink-cdc-sink/index.md
  website/docs/03-Usage Docs/02-setup-spark.md
  website/docs/03-Usage Docs/05-flink-cdc-sync.md
  website/docs/03-Usage Docs/06-flink-lakesoul-connector.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/01-Getting Started/01-setup-local-env.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/01-Getting Started/02-docker-compose.mdx
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/02-Tutorials/02-flink-cdc-sink/index.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/03-Usage Docs/02-setup-spark.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/03-Usage Docs/05-flink-cdc-sync.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/03-Usage Docs/06-flink-lakesoul-connector.md
  website/static/img/lakeSoulModel.png
Labels: documentation, release

#330 [Docs] Add docs for Python and PyTorch
  website/docs/03-Usage Docs/11-machine-learning-support.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/03-Usage Docs/11-machine-learning-support.md
Labels: documentation, python

#331 [Docs] add workspace and rbac docs
  README-CN.md
  README.md
  website/docs/00-intro.md
  website/docs/03-Usage Docs/09-clean-redundant-data.md
  website/docs/03-Usage Docs/11-workspace-and-rbac.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/00-intro.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/03-Usage Docs/09-clean-redundant-data.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/03-Usage Docs/11-workspace-and-rbac.md
Labels: documentation

#310 [Bug]filter should not pushdown before merge on read
  lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/dao/TableInfoDao.java
  lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/dao/TablePathIdDao.java
  lakesoul-flink/src/main/java/org/apache/flink/lakesoul/source/ParquetFilters.java
  lakesoul-flink/src/main/java/org/apache/flink/lakesoul/table/LakeSoulTableSource.java
  lakesoul-spark/src/test/scala/org/apache/spark/sql/lakesoul/commands/UpsertSuiteBase.scala
  rust/lakesoul-io/src/lakesoul_reader.rs
Labels: bug, native-io

#337 [Docs ] Refine flink sql and python docs
  lakesoul-flink/src/main/java/org/apache/flink/lakesoul/table/LakeSoulTableSink.java
  lakesoul-presto/src/main/java/com/facebook/presto/lakesoul/LakeSoulMetadata.java
  lakesoul-presto/src/main/java/com/facebook/presto/lakesoul/LakeSoulRecordCursor.java
  lakesoul-presto/src/main/java/com/facebook/presto/lakesoul/LakeSoulSplitManager.java
  lakesoul-presto/src/main/java/com/facebook/presto/lakesoul/handle/LakeSoulTableLayoutHandle.java
  lakesoul-presto/src/main/java/com/facebook/presto/lakesoul/util/PrestoUtil.java
  website/docs/02-Tutorials/03-snapshot-manage.md
  website/docs/03-Usage Docs/06-flink-lakesoul-connector.md
  website/docs/03-Usage Docs/11-machine-learning-support.md
  website/docs/03-Usage Docs/12-workspace-and-rbac.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/02-Tutorials/03-snapshot-manage.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/02-Tutorials/09-flink-sql-tutorial.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/03-Usage Docs/06-flink-lakesoul-connector.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/03-Usage Docs/11-machine-learning-support.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/03-Usage Docs/12-workspace-and-rbac.md
Labels: documentation

#339 [Release] fix deploy build
  .github/workflows/deployment.yml
  .github/workflows/native-build.yml
Labels: release

#340 [Release] fix deployment maven build and token
  .github/workflows/deployment.yml
Labels: release

#343 [Spark]Spark parquet filter pushdown exactly
  lakesoul-spark/src/main/scala/org/apache/spark/sql/execution/datasources/v2/merge/MergeParquetScan.scala
  lakesoul-spark/src/main/scala/org/apache/spark/sql/execution/datasources/v2/merge/parquet/Native/NativeMergeParquetPartitionReaderFactory.scala
  lakesoul-spark/src/main/scala/org/apache/spark/sql/lakesoul/catalog/LakeSoulScanBuilder.scala
  lakesoul-spark/src/test/scala/org/apache/spark/sql/execution/datasource/parquet/ParquetNativeFilterSuite.scala
  lakesoul-spark/src/test/scala/org/apache/spark/sql/lakesoul/CDCSuite.scala
  lakesoul-spark/src/test/scala/org/apache/spark/sql/lakesoul/commands/UpsertSuiteBase.scala
  rust/lakesoul-io/src/datasource/parquet_source.rs
  rust/lakesoul-io/src/filter/parser.rs
  rust/lakesoul-io/src/lakesoul_io_config.rs
  rust/lakesoul-io/src/sorted_merge/combiner.rs
Labels: enhancement, spark
