Repository lakesoul-io/LakeSoul, pull requests merged in 2023-10, with the labels that each got.

#345 [Meta] fix meta field compatibility in partition info table
  lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/dao/PartitionInfoDao.java
Labels: bug

#348 [Docs] add kyuubi with lakesoul setup doc.
  website/docs/03-Usage Docs/13-setup-kyuubi.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/03-Usage Docs/13-setup-kyuubi.md
Labels: documentation

#350 [NativeIO] Enable parquet prefetch & use stable sort
  lakesoul-spark/src/test/scala/org/apache/spark/sql/lakesoul/benchmark/io/ParquetScanBenchmark.scala
  rust/Cargo.lock
  rust/lakesoul-io/src/datasource/parquet_source.rs
  rust/lakesoul-io/src/lakesoul_io_config.rs
  rust/lakesoul-io/src/lakesoul_reader.rs
  rust/lakesoul-io/src/projection/mod.rs
Labels: enhancement, native-io

#355 [Python][Dataset] Add Ray reading support
  pyproject.toml
  python/lakesoul/huggingface/from_lakesoul.py
  python/lakesoul/ray/__init__.py
  python/lakesoul/ray/read_lakesoul.py
Labels: enhancement, python
