Repository lakesoul-io/LakeSoul, pull requests merged in 2024-02, with the labels that each got.

#440 [Rust] fix panic
  rust/Cargo.lock
  rust/Cargo.toml
  rust/lakesoul-datafusion/Cargo.toml
  rust/lakesoul-datafusion/src/catalog/lakesoul_catalog.rs
  rust/lakesoul-datafusion/src/catalog/lakesoul_namespace.rs
  rust/lakesoul-datafusion/src/catalog/mod.rs
  rust/lakesoul-datafusion/src/datasource/file_format/metadata_format.rs
  rust/lakesoul-datafusion/src/datasource/table_provider.rs
  rust/lakesoul-datafusion/src/error.rs
  rust/lakesoul-datafusion/src/lakesoul_table/helpers.rs
  rust/lakesoul-datafusion/src/lakesoul_table/mod.rs
  rust/lakesoul-datafusion/src/planner/physical_planner.rs
  rust/lakesoul-datafusion/src/serialize/arrow_java.rs
  rust/lakesoul-datafusion/src/test/insert_tests.rs
  rust/lakesoul-datafusion/src/test/upsert_tests.rs
  rust/lakesoul-io-c/build.rs
  rust/lakesoul-io-c/src/lib.rs
  rust/lakesoul-io/Cargo.toml
  rust/lakesoul-io/src/datasource/listing.rs
  rust/lakesoul-io/src/datasource/parquet_source.rs
  rust/lakesoul-io/src/datasource/physical_plan/merge.rs
  rust/lakesoul-io/src/filter/parser.rs
  rust/lakesoul-io/src/helpers.rs
  rust/lakesoul-io/src/lakesoul_io_config.rs
  rust/lakesoul-io/src/lakesoul_reader.rs
  rust/lakesoul-io/src/lakesoul_writer.rs
  rust/lakesoul-io/src/repartition/distributor_channels.rs
  rust/lakesoul-io/src/repartition/mod.rs
  rust/lakesoul-io/src/sorted_merge/combiner.rs
  rust/lakesoul-io/src/sorted_merge/merge_operator.rs
  rust/lakesoul-io/src/sorted_merge/sorted_stream_merger.rs
  rust/lakesoul-io/src/transform.rs
  rust/lakesoul-metadata/Cargo.toml
  rust/lakesoul-metadata/src/error.rs
  rust/lakesoul-metadata/src/lib.rs
  rust/lakesoul-metadata/src/metadata_client.rs
  rust/proto/build.rs
Labels: native-io

#441 [Rust/CI] Add consistency-ci
  .github/workflows/consistency-ci.yml
  .github/workflows/rust-ci.yml
  lakesoul-common/src/main/java/com/dmetasoul/lakesoul/meta/DBManager.java
  lakesoul-spark/src/main/scala/com/dmetasoul/lakesoul/meta/SparkMetaVersion.scala
  lakesoul-spark/src/main/scala/org/apache/spark/sql/lakesoul/schema/ImplicitMetadataOperation.scala
  lakesoul-spark/src/test/scala/org/apache/spark/sql/lakesoul/benchmark/ConsistencyCI.scala
  rust/lakesoul-datafusion/Cargo.toml
  rust/lakesoul-datafusion/src/benchmarks/mod.rs
  rust/lakesoul-datafusion/src/benchmarks/tpch/mod.rs
  rust/lakesoul-datafusion/src/benchmarks/tpch/run.rs
  rust/lakesoul-datafusion/src/catalog/mod.rs
  rust/lakesoul-datafusion/src/datasource/file_format/metadata_format.rs
  rust/lakesoul-datafusion/src/lakesoul_table/mod.rs
  rust/lakesoul-datafusion/src/lib.rs
  rust/lakesoul-datafusion/src/test/integration_tests.rs
  rust/lakesoul-datafusion/src/test/mod.rs
  rust/lakesoul-metadata/src/metadata_client.rs
  script/ci/work-dir/lakesoul.properties
Labels: native-io

#442 [Spark] Compaction bugfix
  lakesoul-spark/src/main/scala/org/apache/spark/sql/lakesoul/commands/CompactionCommand.scala
Labels: bug, spark

#443 [Rust]Fix Consistency CI
  .github/workflows/consistency-ci.yml
  lakesoul-spark/src/test/scala/org/apache/spark/sql/lakesoul/benchmark/ConsistencyCI.scala
  rust/lakesoul-datafusion/src/catalog/mod.rs
  rust/lakesoul-datafusion/src/datasource/file_format/metadata_format.rs
  rust/lakesoul-datafusion/src/lakesoul_table/mod.rs
  rust/lakesoul-datafusion/src/test/catalog_tests.rs
  rust/lakesoul-datafusion/src/test/update_tests.rs
  rust/lakesoul-datafusion/src/test/upsert_tests.rs
Labels: native-io

#444 [Flink] Shade guava for flink package
  lakesoul-common/pom.xml
  lakesoul-common/src/main/scala/com/dmetasoul/lakesoul/meta/DataOperation.scala
  lakesoul-flink/pom.xml
Labels: flink, dependencies

#446 [Project] Bump version
  lakesoul-common/pom.xml
  lakesoul-flink/pom.xml
  lakesoul-presto/pom.xml
  lakesoul-spark/pom.xml
  native-io/lakesoul-io-java/pom.xml
  pom.xml
  website/docs/01-Getting Started/01-setup-local-env.md
  website/docs/01-Getting Started/02-spark-guide.mdx
  website/docs/01-Getting Started/03-Flink-Guide.mdx
  website/docs/02-Tutorials/02-flink-cdc-sink/index.md
  website/docs/02-Tutorials/07-kafka-topics-data-to-lakesoul.md
  website/docs/03-Usage Docs/02-setup-spark.md
  website/docs/03-Usage Docs/05-flink-cdc-sync.md
  website/docs/03-Usage Docs/06-flink-lakesoul-connector.md
  website/docs/03-Usage Docs/08-auto-compaction-task.md
  website/docs/03-Usage Docs/09-clean-redundant-data.md
  website/docs/03-Usage Docs/10-setup-presto.md
  website/docs/03-Usage Docs/13-setup-kyuubi.md
  website/docs/03-Usage Docs/14-export-to-databases.md
  website/docs/03-Usage Docs/15-spark-gluten/index.md
  website/docusaurus.config.js
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/01-Getting Started/01-setup-local-env.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/01-Getting Started/02-spark-guide.mdx
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/01-Getting Started/03-Flink-Guide.mdx
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/02-Tutorials/02-flink-cdc-sink/index.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/02-Tutorials/07-kafka-topics-data-to-lakesoul.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/03-Usage Docs/02-setup-spark.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/03-Usage Docs/05-flink-cdc-sync.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/03-Usage Docs/06-flink-lakesoul-connector.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/03-Usage Docs/08-auto-compaction-task.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/03-Usage Docs/09-clean-redundant-data.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/03-Usage Docs/10-setup-presto.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/03-Usage Docs/13-setup-kyuubi.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/03-Usage Docs/14-export-to-databases.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/03-Usage Docs/15-spark-gluten/index.md
  website/package-lock.json
  website/package.json
  website/variable-inject.js
Labels: documentation, release
