Repository lakesoul-io/LakeSoul, pull requests merged in 2024-01, with the labels that each got.

#385 [Rust]fix hash value to spark_murmur3
  lakesoul-spark/src/test/scala/org/apache/spark/sql/lakesoul/commands/UpsertSuiteBase.scala
  rust/Cargo.lock
  rust/Cargo.toml
  rust/lakesoul-datafusion/src/test/hash_tests.rs
  rust/lakesoul-datafusion/src/test/mod.rs
  rust/lakesoul-io/Cargo.toml
  rust/lakesoul-io/src/hash_utils/mod.rs
  rust/lakesoul-io/src/hash_utils/spark_murmur3.rs
  rust/lakesoul-io/src/lib.rs
  rust/lakesoul-io/src/repartition/mod.rs
Labels: native-io

#387 [BugFix]Fails when create table with nullable hash colmun
  lakesoul-spark/src/main/scala/com/dmetasoul/lakesoul/meta/SparkMetaVersion.scala
  lakesoul-spark/src/main/scala/org/apache/spark/sql/lakesoul/commands/CreateTableCommand.scala
  lakesoul-spark/src/main/scala/org/apache/spark/sql/lakesoul/exception/LakeSoulErrors.scala
  lakesoul-spark/src/main/scala/org/apache/spark/sql/lakesoul/schema/ImplicitMetadataOperation.scala
  lakesoul-spark/src/test/scala/org/apache/spark/sql/lakesoul/TableCreationTests.scala
Labels: bug

#381 [Flink] Add Jdbc cdc sources and sinks
  lakesoul-flink/pom.xml
  lakesoul-flink/src/main/java/com/dmetasoul/lakesoul/meta/external/ExternalDBManager.java
  lakesoul-flink/src/main/java/com/dmetasoul/lakesoul/meta/external/NameSpaceManager.java
  lakesoul-flink/src/main/java/com/dmetasoul/lakesoul/meta/external/mysql/MysqlDBManager.java
  lakesoul-flink/src/main/java/com/dmetasoul/lakesoul/meta/external/mysql/MysqlDataTypeConverter.java
  lakesoul-flink/src/main/java/com/dmetasoul/lakesoul/meta/external/oracle/OracleDBManager.java
  lakesoul-flink/src/main/java/org/apache/flink/lakesoul/entry/JdbcCDC.java
  lakesoul-flink/src/main/java/org/apache/flink/lakesoul/entry/MysqlCdc.java
  lakesoul-flink/src/main/java/org/apache/flink/lakesoul/entry/OracleCdc.java
  lakesoul-flink/src/main/java/org/apache/flink/lakesoul/entry/SyncDatabase.java
  lakesoul-flink/src/main/java/org/apache/flink/lakesoul/sink/LakeSoulDDLSink.java
  lakesoul-flink/src/main/java/org/apache/flink/lakesoul/tool/LakeSoulDDLSinkOptions.java
  lakesoul-flink/src/main/java/org/apache/flink/lakesoul/tool/LakeSoulSinkDatabasesOptions.java
  lakesoul-flink/src/main/java/org/apache/flink/lakesoul/tool/LakeSoulSinkOptions.java
  lakesoul-flink/src/main/java/org/apache/flink/lakesoul/types/BinarySourceRecord.java
  lakesoul-flink/src/test/java/org/apache/flink/lakesoul/test/connector/sink/FlinkCommitterTest.java
  website/docs/03-Usage Docs/05-flink-cdc-sync.md
  website/docs/03-Usage Docs/14-out-of-lake-databases.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/03-Usage Docs/05-flink-cdc-sync.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/03-Usage Docs/14-out-of-lake-databases.md
Labels: enhancement, flink

#388 [Python] fix python meta config parse logic
  python/lakesoul/metadata/native_client.py
  python/lakesoul/spark/testing/run-tests.py
  python/metadata_poc.py
  python/parquet_writer.py
Labels: bug, python

#389 [Project/Doc] Bump version to 2.5.0 and update docs
  README-CN.md
  lakesoul-common/pom.xml
  lakesoul-flink/pom.xml
  lakesoul-presto/pom.xml
  lakesoul-spark/pom.xml
  lakesoul-spark/src/test/scala/org/apache/spark/sql/lakesoul/benchmark/io/ParquetScanBenchmark.scala
  lakesoul-spark/src/test/scala/org/apache/spark/sql/lakesoul/benchmark/io/ParquetWriteBenchmark.scala
  native-io/lakesoul-io-java/pom.xml
  pom.xml
  python/examples/README.md
  python/examples/food101/README.md
  python/examples/imdb/README.md
  python/examples/lakesoul_env.sh
  python/examples/requirements.txt
  python/examples/titanic/README.md
  rust/Cargo.lock
  rust/lakesoul-io-c/Cargo.toml
  rust/lakesoul-io/Cargo.toml
  website/docs/01-Getting Started/00-concepts.md
  website/docs/01-Getting Started/01-setup-local-env.md
  website/docs/01-Getting Started/02-docker-compose.mdx
  website/docs/02-Tutorials/02-flink-cdc-sink/index.md
  website/docs/02-Tutorials/07-kafka-topics-data-to-lakesoul.md
  website/docs/03-Usage Docs/02-setup-spark.md
  website/docs/03-Usage Docs/05-flink-cdc-sync.md
  website/docs/03-Usage Docs/06-flink-lakesoul-connector.md
  website/docs/03-Usage Docs/08-auto-compaction-task.md
  website/docs/03-Usage Docs/09-clean-redundant-data.md
  website/docs/03-Usage Docs/10-setup-presto.md
  website/docs/03-Usage Docs/11-machine-learning-support.md
  website/docs/03-Usage Docs/13-setup-kyuubi.md
  website/docs/03-Usage Docs/14-export-to-databases.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/01-Getting Started/00-concepts.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/01-Getting Started/01-setup-local-env.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/01-Getting Started/02-docker-compose.mdx
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/02-Tutorials/02-flink-cdc-sink/index.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/02-Tutorials/07-kafka-topics-data-to-lakesoul.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/03-Usage Docs/02-setup-spark.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/03-Usage Docs/05-flink-cdc-sync.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/03-Usage Docs/06-flink-lakesoul-connector.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/03-Usage Docs/08-auto-compaction-task.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/03-Usage Docs/09-clean-redundant-data.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/03-Usage Docs/10-setup-presto.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/03-Usage Docs/11-machine-learning-support.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/03-Usage Docs/13-setup-kyuubi.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/03-Usage Docs/14-export-to-databases.md
  website/static/img/wechat.png
Labels: documentation, release

#400 [Rust] Update arrow rs dependencies
  .github/workflows/rust-clippy.yml
  rust/Cargo.lock
Labels: native-io

#403 [Docs] Add Spark Getting Started Guide
  website/docs/01-Getting Started/03-spark-guide.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/01-Getting Started/03-spark-guide.md
Labels: documentation

#408 [Docs] Update docs format
  website/docs/01-Getting Started/01-setup-local-env.md
  website/docs/01-Getting Started/02-spark-guide.mdx
  website/docs/01-Getting Started/03-Flink-Guide.mdx
  website/docs/03-Usage Docs/03-spark-api-docs.md
  website/docs/03-Usage Docs/13-setup-kyuubi.md
  website/docusaurus.config.js
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/01-Getting Started/01-setup-local-env.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/01-Getting Started/02-spark-guide.mdx
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/01-Getting Started/03-Flink-Guide.mdx
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/03-Usage Docs/03-spark-api-docs.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/03-Usage Docs/13-setup-kyuubi.md
Labels: documentation

#411 [Docs]Fine check usage cases of spark guide
  website/docs/01-Getting Started/02-spark-guide.mdx
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/01-Getting Started/02-spark-guide.mdx
Labels: documentation

#413 [Website] fix website zh-Hans Homepage docs link
  website/i18n/zh-Hans/code.json
  website/src/pages/index.js
Labels: documentation

#414 [Docs] add pyspark in spark-guide
  lakesoul-spark/src/main/scala/org/apache/spark/sql/catalyst/parser/extensions/LakeSoulSparkSqlExtensionsParser.scala
  website/docs/01-Getting Started/02-spark-guide.mdx
  website/docs/02-Tutorials/03-snapshot-manage.md
  website/docs/03-Usage Docs/03-spark-api-docs.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/01-Getting Started/02-spark-guide.mdx
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/02-Tutorials/03-snapshot-manage.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/03-Usage Docs/03-spark-api-docs.md
Labels: documentation

#417 [Spark/Rust/Test] Fix MergeOperatorSuite && Disable 3 cases
  lakesoul-spark/src/main/scala/org/apache/spark/sql/execution/datasources/v2/merge/parquet/Native/NativeMergeParquetPartitionReaderFactory.scala
  lakesoul-spark/src/main/scala/org/apache/spark/sql/execution/datasources/v2/merge/parquet/batch/merge_operator/MergeOperator.scala
  lakesoul-spark/src/test/scala/org/apache/spark/sql/execution/datasource/MergeOperatorSuite.scala
  lakesoul-spark/src/test/scala/org/apache/spark/sql/lakesoul/test/TestUtils.scala
  rust/lakesoul-io/src/sorted_merge/merge_operator.rs
Labels: bug, spark, native-io

#415 [Spark] Implement columnar write for compaction
  lakesoul-spark/pom.xml
  lakesoul-spark/src/main/scala/org/apache/spark/sql/execution/datasources/LakeSoulFileWriter.scala
  lakesoul-spark/src/main/scala/org/apache/spark/sql/execution/datasources/v2/merge/MergeParquetScan.scala
  lakesoul-spark/src/main/scala/org/apache/spark/sql/execution/datasources/v2/parquet/NativeParquetColumnarOutputWriter.scala
  lakesoul-spark/src/main/scala/org/apache/spark/sql/execution/datasources/v2/parquet/NativeParquetFileFormat.scala
  lakesoul-spark/src/main/scala/org/apache/spark/sql/execution/datasources/v2/parquet/NativeParquetOutputWriter.scala
  lakesoul-spark/src/main/scala/org/apache/spark/sql/lakesoul/TransactionalWrite.scala
  lakesoul-spark/src/main/scala/org/apache/spark/sql/lakesoul/catalog/LakeSoulScanBuilder.scala
  lakesoul-spark/src/main/scala/org/apache/spark/sql/lakesoul/commands/CompactionCommand.scala
  lakesoul-spark/src/main/scala/org/apache/spark/sql/lakesoul/rules/SetPartitionAndOrdering.scala
  lakesoul-spark/src/main/scala/org/apache/spark/sql/lakesoul/schema/ImplicitMetadataOperation.scala
  lakesoul-spark/src/main/scala/org/apache/spark/sql/vectorized/ArrowFakeRow.scala
  lakesoul-spark/src/test/resources/log4j2-test.properties
  lakesoul-spark/src/test/scala/org/apache/spark/sql/lakesoul/DataFrameWriterV2Suite.scala
  lakesoul-spark/src/test/scala/org/apache/spark/sql/lakesoul/LakeSoulSinkSuite.scala
  lakesoul-spark/src/test/scala/org/apache/spark/sql/lakesoul/TableCreationTests.scala
  lakesoul-spark/src/test/scala/org/apache/spark/sql/lakesoul/commands/AlterTableTests.scala
  lakesoul-spark/src/test/scala/org/apache/spark/sql/lakesoul/commands/CompactionSuite.scala
  lakesoul-spark/src/test/scala/org/apache/spark/sql/lakesoul/rules/LakeSoulGlutenCompatSuite.scala
  lakesoul-spark/src/test/scala/org/apache/spark/sql/lakesoul/schema/CaseSensitivitySuite.scala
  lakesoul-spark/src/test/scala/org/apache/spark/sql/lakesoul/schema/InvariantEnforcementSuite.scala
  native-io/lakesoul-io-java/src/main/java/com/dmetasoul/lakesoul/lakesoul/io/NativeIOWriter.java
  native-io/lakesoul-io-java/src/main/java/com/dmetasoul/lakesoul/lakesoul/io/jnr/LibLakeSoulIO.java
  rust/lakesoul-io-c/lakesoul_c_bindings.h
  rust/lakesoul-io-c/src/lib.rs
Labels: enhancement, spark

#419 [Docs] Update docs to 2.5.1
  python/examples/food101/README.md
  python/examples/imdb/README.md
  python/examples/titanic/README.md
  website/docs/01-Getting Started/01-setup-local-env.md
  website/docs/01-Getting Started/02-spark-guide.mdx
  website/docs/01-Getting Started/03-Flink-Guide.mdx
  website/docs/02-Tutorials/02-flink-cdc-sink/index.md
  website/docs/02-Tutorials/07-kafka-topics-data-to-lakesoul.md
  website/docs/03-Usage Docs/02-setup-spark.md
  website/docs/03-Usage Docs/05-flink-cdc-sync.md
  website/docs/03-Usage Docs/06-flink-lakesoul-connector.md
  website/docs/03-Usage Docs/08-auto-compaction-task.md
  website/docs/03-Usage Docs/09-clean-redundant-data.md
  website/docs/03-Usage Docs/10-setup-presto.md
  website/docs/03-Usage Docs/13-setup-kyuubi.md
  website/docs/03-Usage Docs/14-export-to-databases.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/01-Getting Started/01-setup-local-env.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/01-Getting Started/02-spark-guide.mdx
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/01-Getting Started/03-Flink-Guide.mdx
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/02-Tutorials/02-flink-cdc-sink/index.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/02-Tutorials/07-kafka-topics-data-to-lakesoul.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/03-Usage Docs/02-setup-spark.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/03-Usage Docs/05-flink-cdc-sync.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/03-Usage Docs/06-flink-lakesoul-connector.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/03-Usage Docs/08-auto-compaction-task.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/03-Usage Docs/09-clean-redundant-data.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/03-Usage Docs/10-setup-presto.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/03-Usage Docs/13-setup-kyuubi.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/03-Usage Docs/14-export-to-databases.md
Labels: documentation

#420 [Spark/Rust] Fix Unicode column name at native io
  lakesoul-spark/src/test/scala/org/apache/spark/sql/execution/datasource/parquet/ParquetNativeFilterSuite.scala
  native-io/lakesoul-io-java/src/main/java/com/dmetasoul/lakesoul/lakesoul/io/NativeIOBase.java
  native-io/lakesoul-io-java/src/main/java/com/dmetasoul/lakesoul/lakesoul/io/NativeIOReader.java
  native-io/lakesoul-io-java/src/main/java/com/dmetasoul/lakesoul/lakesoul/io/NativeIOWriter.java
  native-io/lakesoul-io-java/src/main/java/com/dmetasoul/lakesoul/lakesoul/io/jnr/LibLakeSoulIO.java
  rust/lakesoul-io/src/filter/parser.rs
Labels: bug, native-io

#421 Support sqlserver CDC
  lakesoul-flink/pom.xml
  lakesoul-flink/src/main/java/org/apache/flink/lakesoul/entry/JdbcCDC.java
Labels: enhancement

#425 [Docs] Fix python doc typos
  python/examples/README.md
  website/docs/03-Usage Docs/11-machine-learning-support.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/03-Usage Docs/11-machine-learning-support.md
Labels: documentation

#422 [Spark/Rust] Support filter on nesting column name
  lakesoul-spark/src/test/scala/org/apache/spark/sql/execution/datasource/parquet/ParquetNativeFilterSuite.scala
  rust/lakesoul-io/src/filter/parser.rs
  rust/lakesoul-io/src/transform.rs
Labels: spark, native-io

#423 [Docs] Add docs and recent blogs
  website/babel.config.js
  website/blog/2023-12-01-lakesoul-introduction/index.mdx
  website/blog/2024-01-10-lakesoul-native-io/index.mdx
  website/canvas-loader.js
  website/docs/03-Usage Docs/05-flink-cdc-sync.md
  website/docs/03-Usage Docs/15-spark-gluten/index.md
  website/docs/03-Usage Docs/15-spark-gluten/lakesoul-gluten.png
  website/docusaurus.config.js
  website/i18n/zh-Hans/docusaurus-plugin-content-blog/2023-12-01-lakesoul-introduction/index.mdx
  website/i18n/zh-Hans/docusaurus-plugin-content-blog/2024-01-10-lakesoul-native-io/index.mdx
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/03-Usage Docs/05-flink-cdc-sync.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/03-Usage Docs/15-spark-gluten/index.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/03-Usage Docs/15-spark-gluten/lakesoul-gluten.png
  website/package-lock.json
  website/package.json
  website/src/components/LakeSoulIntroductionPdfView.tsx
  website/src/components/NativeIOPdfViewer.tsx
  website/static/lakesoul-introduction-en.pdf
  website/static/lakesoul-introduction.pdf
  website/static/nativeio-en.pdf
  website/static/nativeio.pdf
Labels: documentation

#426 [Flink/Rust] Adjust rolling file logic to reduce memory usage during write
  lakesoul-flink/src/main/java/org/apache/flink/lakesoul/sink/LakeSoulRollingPolicyImpl.java
  lakesoul-flink/src/main/java/org/apache/flink/lakesoul/sink/state/LakeSoulMultiTableSinkCommittable.java
  lakesoul-flink/src/main/java/org/apache/flink/lakesoul/sink/writer/LakeSoulWriterBucket.java
  lakesoul-flink/src/main/java/org/apache/flink/lakesoul/sink/writer/NativeParquetWriter.java
  lakesoul-flink/src/main/java/org/apache/flink/lakesoul/table/LakeSoulDynamicTableFactory.java
  lakesoul-flink/src/main/java/org/apache/flink/lakesoul/table/LakeSoulTableSource.java
  lakesoul-flink/src/main/java/org/apache/flink/lakesoul/tool/FlinkUtil.java
  lakesoul-flink/src/main/java/org/apache/flink/lakesoul/tool/LakeSoulSinkOptions.java
  rust/lakesoul-io/src/lakesoul_io_config.rs
  rust/lakesoul-io/src/lakesoul_reader.rs
  rust/lakesoul-io/src/lakesoul_writer.rs
  rust/lakesoul-io/src/sorted_merge/sorted_stream_merger.rs
  website/docs/03-Usage Docs/06-flink-lakesoul-connector.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/03-Usage Docs/06-flink-lakesoul-connector.md
Labels: bug, enhancement, flink, native-io

#431 [Rust] Enable metadata max retries
  rust/lakesoul-metadata/src/metadata_client.rs
Labels: bug, native-io

#430 [Flink] Fix CDC entry db name
  lakesoul-flink/src/main/java/org/apache/flink/lakesoul/entry/JdbcCDC.java
Labels: bug, flink

#432 [Rust] Keep only push down rules in datafusion
  rust/lakesoul-io/src/lakesoul_io_config.rs
Labels: enhancement, native-io

#429 [Rust] Datafusion Catalog Support
  rust/.gitignore
  rust/Cargo.lock
  rust/Cargo.toml
  rust/lakesoul-datafusion/Cargo.toml
  rust/lakesoul-datafusion/src/catalog/lakesoul_catalog.rs
  rust/lakesoul-datafusion/src/catalog/lakesoul_namespace.rs
  rust/lakesoul-datafusion/src/catalog/mod.rs
  rust/lakesoul-datafusion/src/datasource/file_format/metadata_format.rs
  rust/lakesoul-datafusion/src/datasource/table_provider.rs
  rust/lakesoul-datafusion/src/error.rs
  rust/lakesoul-datafusion/src/lakesoul_table/helpers.rs
  rust/lakesoul-datafusion/src/lakesoul_table/mod.rs
  rust/lakesoul-datafusion/src/lib.rs
  rust/lakesoul-datafusion/src/planner/physical_planner.rs
  rust/lakesoul-datafusion/src/serialize/arrow_java.rs
  rust/lakesoul-datafusion/src/test/catalog_tests.rs
  rust/lakesoul-datafusion/src/test/hash_tests.rs
  rust/lakesoul-datafusion/src/test/insert_tests.rs
  rust/lakesoul-datafusion/src/test/mod.rs
  rust/lakesoul-datafusion/src/test/upsert_tests.rs
  rust/lakesoul-io-c/src/lib.rs
  rust/lakesoul-io/Cargo.toml
  rust/lakesoul-io/src/datasource/file_format.rs
  rust/lakesoul-io/src/datasource/listing.rs
  rust/lakesoul-io/src/datasource/parquet_source.rs
  rust/lakesoul-io/src/datasource/physical_plan/merge.rs
  rust/lakesoul-io/src/filter/parser.rs
  rust/lakesoul-io/src/hash_utils/mod.rs
  rust/lakesoul-io/src/hash_utils/spark_murmur3.rs
  rust/lakesoul-io/src/lakesoul_io_config.rs
  rust/lakesoul-io/src/lakesoul_reader.rs
  rust/lakesoul-io/src/lakesoul_writer.rs
  rust/lakesoul-io/src/lib.rs
  rust/lakesoul-io/src/repartition/mod.rs
  rust/lakesoul-io/src/sorted_merge/merge_operator.rs
  rust/lakesoul-io/src/sorted_merge/sort_key_range.rs
  rust/lakesoul-io/src/sorted_merge/sorted_stream_merger.rs
  rust/lakesoul-io/src/transform.rs
  rust/lakesoul-metadata/Cargo.toml
  rust/lakesoul-metadata/src/error.rs
  rust/lakesoul-metadata/src/lib.rs
  rust/lakesoul-metadata/src/metadata_client.rs
  website/i18n/zh-Hans/code.json
Labels: enhancement, native-io

#433 [Flink] Fix non-primary key table's sink parallelism
  lakesoul-flink/src/main/java/org/apache/flink/lakesoul/table/LakeSoulTableSink.java
  lakesoul-flink/src/test/java/org/apache/flink/lakesoul/test/connector/sink/LakeSoulTableSinkCase.java
  lakesoul-flink/src/test/java/org/apache/flink/lakesoul/test/schema/SchemaMigrationTest.java
Labels: bug, flink

#434 [Python] Fix python host build
  .github/workflows/maven-test.yml
  .github/workflows/rust-ci.yml
  .gitignore
  cpp/CMakeLists.txt
  docker/lakesoul-docker-compose-env/docker-compose.yml
  lakesoul-flink/src/test/resources/log4j2-test.properties
  lakesoul-spark/src/test/scala/org/apache/spark/sql/lakesoul/benchmark/LargeColumnsBench.scala
  lakesoul-spark/src/test/scala/org/apache/spark/sql/lakesoul/commands/CompactionSuite.scala
  pyproject.toml
  python/host_build_wheel.py
  python/tests/arrow/test_lakesoul_read.py
  python/tests/spark/__init__.py
  python/tests/spark/test_lakesoultable.py
  python/tests/spark/testing/__init__.py
  python/tests/spark/testing/log4j.properties
  python/tests/spark/testing/run-tests.py
  python/tests/spark/testing/utils.py
Labels: bug, python

#437 [Docs] Add deployment docs
  website/docs/04-Deployment/01-Postgres-Cluster.md
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current.json
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/04-Deployment/01-Postgres-Cluster.md
Labels: documentation

#438 [Rust] fix catalog unittest
  .github/workflows/maven-test.yml
  .github/workflows/rust-ci.yml
  rust/lakesoul-datafusion/src/catalog/lakesoul_catalog.rs
  rust/lakesoul-datafusion/src/catalog/lakesoul_namespace.rs
  rust/lakesoul-datafusion/src/datasource/file_format/metadata_format.rs
  rust/lakesoul-datafusion/src/lakesoul_table/mod.rs
  rust/lakesoul-datafusion/src/test/catalog_tests.rs
  rust/lakesoul-io/src/datasource/listing.rs
  rust/lakesoul-metadata/src/metadata_client.rs
Labels: native-io

#436 [Flink]Fix create table options
  lakesoul-flink/src/main/java/org/apache/flink/lakesoul/metadata/LakeSoulCatalog.java
Labels: bug, flink
